<?xml version="1.0" encoding="utf-8"?><Database Name="drankregristratie" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-BG1SF22R\SQLEXPRESS;Initial Catalog=drankregristratie;Integrated Security=True" SettingsObjectName="drankregrestratie.Properties.Settings" SettingsPropertyName="drankregristratieConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Drankregristratie" Member="Drankregristraties">
    <Type Name="Drankregristratie">
      <Column Name="DrankID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naam" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>